### ISSUE TITLE
Update patches for Kanidm release 1.2.0

### ISSUE THREAD

**Issue by Lynnaut** [oddlama/kanidm-provision#1]
I've tried migrating the patches and managed to get it to compile but the application fails to start.

**Comment by oddlama** [comment]
I'm taking a look right now :)

**Comment by oddlama** [comment]
Patches seem to work fine after reapplying, let's see what the NixOS tests say.

**Comment by oddlama** [comment]
Everything is working correctly in kanidm-provision from what I can tell.

If you were instead specifically referring to the NixOS module PR (https://github.com/NixOS/nixpkgs/pull/251598), then you are right in that it isn't starting right now. But that is just because of a systemd post start script that needed adjustments for 1.2.0. I've updated the PR already (but the tests won't run through currently because of a bug in kanidm preventing logout from working).
