### ISSUE TITLE
Updated kanidm nix module supersede kanidm-provision now?

### ISSUE THREAD

**Issue by mannp** [oddlama/kanidm-provision#8]
Hi

Does your PR to the kanidm nix module https://github.com/nixos/nixpkgs/pull/251598 supersede the use of kanidm-provision separately?

Should I novate my json config for this tool to the nix module or will they work both together or separately.

Thanks.

**Comment by oddlama** [comment]
I made the PR primarily to provide a native interface to this provisioning tool in nixos. I would recommend using the module since it does some extra checks and adds some level of convenience if you are already on nixos, but of course you can just as well use it as standalone tool if you already have a working state file.

Just don't use them simultaneously, since the entity tracking cannot discern between the two provisioning tool calls.

**Comment by mannp** [comment]
Okay thanks, that explains it.
